[build]
  base    = "app-next"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION        = "22"
  CLICKUP_FOLDER_ID   = ""
  CLICKUP_LIST_ID     = ""
  CLICKUP_API_TOKEN   = ""
  DATABASE_URL        = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"

